---
title: "cp-greeninfrastructure"
author: "Genevieve Chiong and Kristin Gill"
date: "10/26/2021"
output: 
   html_document:
     theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(swmmr)
library(here)
library(sf)
library(berryFunctions)
library(readr)
library(lwgeom)
library(janitor)
library(units)
```

Read in the data, set crs to WGS 84, and clip to wailupe
```{r}
wailupe <- read_sf(here("data", "wailupe.shp"))
wailupe <- st_transform(wailupe, crs = 4326)

buildings <- read_sf(here("data", "buildings.shp"))
buildings <- st_transform(buildings, crs = 4326) %>% 
  st_make_valid()
buildings_clip <- buildings[wailupe, op = st_intersects]

wetlands <- read_sf(here("data", "wetlands.shp"))
wetlands <- st_transform(wetlands, crs = 4326)
wetlands_clip <- wetlands[wailupe, op = st_intersects]

stormwater_structures <- read_sf(here("data", "stormwater_structures.shp"))
stormwater_structures <- st_transform(stormwater_structures, crs = 4326)
stormwater_structures_clip <- stormwater_structures[wailupe, op = st_intersects]

conduits <- read_sf(here("data", "conduits.shp"))
conduits <- st_transform(conduits, crs = 4326)
conduits_clip <- conduits[wailupe, op = st_intersects]

parks <- read_sf(here("data", "parks.shp"))
parks <- st_transform(parks, crs = 4326)
parks_clip <- parks[wailupe, op = st_intersects]

flood_zones <- read_sf(here("data", "flood_zones.shp")) # need to get to look like flood_risk
flood_zones <- st_transform(flood_zones, crs = 4326) %>% 
  st_make_valid()
flood_zones_clip <- flood_zones[wailupe, op = st_intersects]

critical_habitat <- read_sf(here("data", "critical_habitat.shp"))
critical_habitat <- st_transform(critical_habitat, crs = 4326)
critical_habitat_clip <- critical_habitat[wailupe, op = st_intersects]

rm(buildings)
rm(wetlands)
rm(stormwater_structures)
rm(conduits)
rm(parks)
rm(parking_lot)
rm(flood_zones)
rm(critical_habitat)
gc()
```

Roads and Sidewalks
```{r}
roads <- read_sf(here("data", "roads.shp"))
roads <- st_transform(roads, crs = 4326)
roads_clip <- roads[wailupe, op = st_intersects]

# buffer road lines to create polygon roads
roads_buffer <- roads_clip %>% 
  st_buffer(3)

# buffer roads to create sidewalks

sidewalks <- roads_buffer %>% 
  st_buffer(2)

sidewalks <- st_difference(sidewalks, roads_buffer)

sidewalks <- st_make_valid(sidewalks)

ggplot() +
  geom_sf(data = wailupe) +
  geom_sf(data = sidewalks, col = "blue") +
  geom_sf(data = roads_buffer, col = "black")
  
```

```{r}
rm(roads)
rm(roads_clip)
gc()
```

Site Locator Tool
```{r}
parking_lot <- read_sf(here("data", "parking_lot.shp"))
st_crs(parking_lot) = 4326
parking_lot <- st_transform(parking_lot, crs = 4326)
parking_lot_clip <- parking_lot[wailupe, op = st_intersects]

rm(parking_lot)
gc()

biorwu <- st_union(sidewalks, parking_lot_clip)

rm(parking_lot_clip)
gc()

biornu <- 
vgsw <-

```

```{r}
# this one is not in the right location but has the percent impervious 
inp <- read_inp(here("data", "SWMM_input.inp"))

junctions <- inp %>% 
  junctions_to_sf()

percent_imperv <- inp %>% 
  subcatchments_to_sf()

st_crs(percent_imperv) = 4326

percent_imperv <- st_transform(percent_imperv, crs = 4326)

percent_imperv <- st_make_valid(percent_imperv)
```

Subcatchments
```{r}
subcatchments <- read_sf(here("data", "subcatchments", "subcatchments_wailupe_final.shp")) %>% 
  clean_names() %>% 
  select(objectid_1, geometry)

subcatchments <- st_transform(subcatchments, crs = 4326)

subcatchments <- st_make_valid(subcatchments)

plot(subcatchments)
```

LID info
```{r}
lid <- read_csv(here("data", "LID_info_to_edit.csv")) %>% 
  mutate(LID = c("PRPV", "INFT", "VGSW", "nothing", "nothing")) %>% 
  filter(LID == c("PRPV", "INFT", "VGSW"))

write_csv(lid, "LID_info.csv")
```

Areas Intersect - Biornu
```{r}
optim_biornu <- read_sf(here("data", "biornu.shp"))

optim_biornu <- st_transform(optim_biornu, crs = 4326)

optim_biornu <- st_make_valid(optim_biornu)

optim_biornu_intersect <-st_intersection(subcatchments, optim_biornu) %>% 
  insertRows(c(1,2,3,38,41,43,50,64, 83:87,92,94)) %>% 
  mutate(objectid_1 = seq.int(1:97))

optim_biornu_intersect$area_biornu <- st_area(optim_biornu_intersect$geometry)

biornu <- optim_biornu_intersect %>% 
  mutate(num_gi_bior = area_biornu/14) %>% #10 feet by 15 feet = 14 square meters
  select(!c(OBJECTID, Shape_Leng, Shape_Area))

ggplot() +
  geom_sf(data = subcatchments, aes(fill = objectid_1))+
  geom_sf(data = optim_biornu, col = "white") +
  theme_minimal()
```

Areas Intersect - trbx
```{r}
optim_trbx <- read_sf(here("data", "trbx.shp"))

optim_trbx <- st_transform(optim_trbx, crs = 4326)

optim_trbx <- sf::st_make_valid(optim_trbx)

optim_trbx_intersect <- st_intersection(subcatchments, optim_trbx) %>% 
  insertRows(c(2,38,41,43,50,64, 83:87,92,94)) %>% 
  mutate(objectid_1 = seq.int(1:97))

optim_trbx_intersect$area_trbx <- st_area(optim_trbx_intersect$geometry)

trbx <- optim_trbx_intersect %>% 
  mutate(num_gi_trbx = area_trbx/13.4) %>% 
  select(!c(OBJECTID, Shape_Leng, Shape_Area))

ggplot() +
  geom_sf(data = subcatchments, aes(fill = objectid_1))+
  geom_sf(data = optim_trbx, col = "white") +
  theme_minimal()
```

Area Intersect - prpv
```{r}
optim_prpv <- read_sf(here("data", "prpv.shp"))

optim_prpv <- st_transform(optim_prpv, crs = 4326)

optim_prpv <- st_make_valid(optim_prpv)

optim_prpv_intersect <- st_intersection(subcatchments, optim_prpv) %>% 
  insertRows(c(1,2,3,38,41,43,50,64, 83:87,92,94)) %>% 
  mutate(objectid_1 = seq.int(1:97))

optim_prpv_intersect$area_prpv <- st_area(optim_prpv_intersect$geometry)

prpv <- optim_prpv_intersect %>% 
  mutate(num_gi_prpv = area_prpv/464.5) %>% 
  select(!c(OBJECTID, Shape_Leng, Shape_Area))

ggplot() +
  geom_sf(data = subcatchments, aes(fill = objectid_1))+
  geom_sf(data = optim_prpv, col = "white") +
  theme_minimal()
```

Area Intersect - vgsw
```{r}
optim_vgsw <- read_sf(here("data", "vgsw.shp"))

optim_vgsw <- st_transform(optim_vgsw, crs = 4326)

optim_vgsw <- st_make_valid(optim_vgsw)

optim_vgsw_intersect <- st_intersection(subcatchments, optim_vgsw) %>% 
  insertRows(c(2,38,41,43,50,64, 83:87,92,94)) %>% 
  mutate(objectid_1 = seq.int(1:97))

optim_vgsw_intersect$area_vgsw <- st_area(optim_vgsw_intersect$geometry)

vgsw <- optim_vgsw_intersect %>% 
  mutate(num_gi_vgsw = area_vgsw/83.6) %>% 
  select(!c(OBJECTID, Shape_Leng, Shape_Area))

ggplot() +
  geom_sf(data = subcatchments, aes(fill = objectid_1))+
  geom_sf(data = optim_vgsw, col = "white") +
  theme_minimal()
```

Area Intersect - ftpb
```{r}
optim_ftpb <- read_sf(here("data", "ftpd.shp"))

optim_ftpb <- st_transform(optim_ftpb, crs = 4326)

optim_ftpb <- st_make_valid(optim_ftpb)

optim_ftpb_intersect <- st_intersection(subcatchments, optim_ftpb) %>% 
  insertRows(c(1,2,3,38,41,43,50,64, 83:87,92,94)) %>% 
  mutate(objectid_1 = seq.int(1:97))

optim_ftpb_intersect$area_ftpb <- st_area(optim_ftpb_intersect$geometry)

ftpb <- optim_ftpb_intersect %>% 
  mutate(num_gi_ftpd = area_ftpb/83.6) %>% 
  select(!c(OBJECTID, Shape_Leng, Shape_Area))

ggplot() +
  geom_sf(data = subcatchments, aes(fill = objectid_1))+
  geom_sf(data = optim_ftpb, col = "white") +
  theme_minimal()
```

Area Intersect - inft
```{r}
optim_inft <- read_sf(here("data", "inft.shp"))

optim_inft <- st_transform(optim_inft, crs = 4326)

optim_inft <- st_make_valid(optim_inft)

optim_inft_intersect <- st_intersection(subcatchments, optim_inft) %>% 
  insertRows(c(2,5,6,8,9,13,14,15,18,19,21,22,23,26:71,75,76,77,80:87,89:96)) %>% 
  mutate(objectid_1 = seq.int(1:97))

optim_inft_intersect$area_inft <- st_area(optim_inft_intersect$geometry)

inft <- optim_inft_intersect %>% 
  mutate(num_gi_ift = area_inft/83.6) %>% 
  select(!c(OBJECTID, Shape_Leng, Shape_Area))

ggplot() +
  geom_sf(data = subcatchments, aes(fill = objectid_1))+
  geom_sf(data = optim_inft, col = "white") +
  theme_minimal()
```

Basin_info File
```{r}
basin_info_1 <- st_join(vgsw, prpv, left = TRUE) %>% 
  distinct(objectid_1.x, .keep_all = TRUE)

basin_info_2 <- st_join(biornu, inft) %>% 
  distinct(objectid_1.x, .keep_all = TRUE)

basin_info <- st_join(basin_info_1, basin_info_2) %>% 
  distinct(objectid_1.x.x, .keep_all = TRUE) %>% 
  select(!c(area_vgsw, area_inft, area_biornu, area_prpv, objectid_1.x.y, objectid_1.y.x, objectid_1.y.y)) %>%
  rename(Name = objectid_1.x.x) %>% 
  st_drop_geometry() %>% 
  rename(VGSW = num_gi_vgsw) %>% 
  rename(INFT = num_gi_ift) %>% 
  rename(PRPV = num_gi_prpv) %>% 
  rename(BIOR = num_gi_bior)

basin_info <- merge(basin_info, percent_imperv) %>% 
  select(Name, Area, Perc_Imperv, VGSW, INFT, PRPV, BIOR) %>% 
  rename(Basin = Name) %>% 
  mutate(S = "S") %>% 
  mutate(Basin = as.character(Basin)) %>% 
  unite(Basin, S, Basin, sep = "") %>% 
  units::drop_units()

basin_info[is.na(basin_info)] <- 0.001

write_csv(basin_info, "Basin_info.csv")
```